import { Injectable } from '@angular/core';

export interface SearchResult {
  title: string;
  route: string;
  snippet: string;
  matchedText: string;
}

interface GuideIndex {
  title: string;
  route: string;
  content: string;
}

@Injectable({
  providedIn: 'root',
})
export class SearchService {
  private readonly guideIndex: GuideIndex[] = [
    {
      title: 'Introduction',
      route: '/guides/introduction',
      content: `Introduction uv covers the entire Python development cycle from installing the language itself and testing quick scripts to managing massive projects that need support for multiple platforms and versions of Python. Overview uv's interface can be broken down into sections which are usable independently or together. Each section handles a specific aspect of Python development. Python Version Management Install and manage multiple Python versions. Package Management Install update and remove packages. Project Management Create and work with Python projects. Tools Run and install CLI tools. Scripts Execute standalone Python scripts. Publishing Build and publish packages.`,
    },
    {
      title: 'Projects',
      route: '/guides/projects',
      content: `Projects uv simplifies Python project management by centralizing everything in the standard pyproject.toml file. Forget about manually setting up virtual environments or dealing with outdated requirements files. Initialize a new project Creates the basic structure of a Python project with uv init. Automatically generates essential files pyproject.toml main.py and Git configuration. uv init my-project. Add dependencies Installs and registers packages in your project with uv add. Automatically adds dependencies to pyproject.toml and installs them in the virtual environment. uv add requests flask. uv add pytest dev. Remove dependencies Uninstalls and removes packages from your project with uv remove. Cleans both the virtual environment and the references in pyproject.toml. uv remove requests. Sync environment Synchronizes project dependencies with the virtual environment using uv sync. Ensures the environment exactly matches what's defined in pyproject.toml. uv sync. Run commands Executes scripts or commands within the project virtual environment with uv run. Automatically activates the environment and runs the command without manual activation. uv run python main.py. View dependency tree Shows the complete dependency tree with uv tree. Displays all direct and indirect dependencies useful for resolving version conflicts. uv tree. Build package Compiles and packages your project for distribution with uv build. Generates wheel and source files in the dist folder ready for publishing. uv build. Publish package Publishes your package to a Python index PyPI or other with uv publish. Uploads the files generated by uv build to the configured repository. uv publish.`,
    },
    {
      title: 'Python version',
      route: '/guides/python-version',
      content: `Python version If Python is already installed on your system uv will detect and use it without configuration. However uv can also install and manage Python versions. uv automatically installs missing Python versions as needed. Install Python Install Python versions managed by uv. You don't need Python installed beforehand. uv python install. uv python install 3.12. List Python versions View available Python versions installed by uv and those available for installation. uv python list. Find Python version Find an installed Python version matching a specific requirement. uv python find 3.12. Uninstall Python version Uninstall a Python version that was installed by uv. uv python uninstall 3.11.9.`,
    },
    {
      title: 'Package',
      route: '/guides/package',
      content: `Package uv supports building Python packages into source and binary distributions via uv build and uploading them to a registry with uv publish. Build package Build your Python project and create distribution artifacts in the dist directory. uv build. Publish package Upload your built packages to a registry PyPI by default or a custom index. uv publish. Update version Update the version of your project in pyproject.toml. uv version. uv version bump patch.`,
    },
    {
      title: 'Scripts',
      route: '/guides/scripts',
      content: `Scripts A Python script is a file intended for standalone execution. Using uv to execute scripts ensures that script dependencies are managed without manually managing environments. Run a script Execute a Python script with uv. Dependencies are automatically managed in a temporary environment. uv run script.py. Run with dependencies Run a script with additional packages installed in a temporary environment. uv run with requests script.py. Add script dependency Add a dependency to a script that uses inline metadata. Updates the script's dependency declarations. uv add script requests script.py. Remove script dependency Remove a dependency from a script that uses inline metadata. uv remove script requests script.py.`,
    },
    {
      title: 'Tools',
      route: '/guides/tools',
      content: `Tools Running and installing tools published to Python package indexes like ruff or black. Run tool on demand Use uvx to run a tool in a temporary environment without installing it. Perfect for one-off commands. uvx ruff check. Run installed tool Run a tool that has been installed with uv tool install. uv tool run ruff check. Install tool Install a tool user-wide for persistent access across your system. uv tool install ruff. Uninstall tool Uninstall a tool that was installed with uv tool install. uv tool uninstall ruff. List tools List all tools installed user-wide. uv tool list. Update shell Update the shell to include tool executables in your PATH. Run this after installing tools. uv tool update-shell.`,
    },
    {
      title: 'The pip interface',
      route: '/guides/pip-interface',
      content: `The pip interface Manually managing environments and packages intended to be used in legacy workflows or cases where the high-level commands do not provide enough control. Create virtual environment Create a new virtual environment. Replaces venv and virtualenv. uv venv. uv venv python 3.12. Install packages Install packages into the current environment. Replaces pip install. uv pip install requests flask. uv pip install r requirements.txt. Show package info Show details about an installed package. Replaces pip show. uv pip show requests. List packages List all installed packages in the current environment. Replaces pip list. uv pip list. Freeze packages List installed packages and their versions in a format suitable for requirements files. uv pip freeze. Check packages Check that the current environment has compatible packages and no conflicts. uv pip check. Uninstall packages Uninstall packages from the current environment. Replaces pip uninstall. uv pip uninstall requests. Dependency tree View the dependency tree for the current environment. Replaces pipdeptree. uv pip tree. Compile requirements Compile requirements into a lockfile. Replaces pip-compile. uv pip compile requirements.in o requirements.txt. Sync environment Sync an environment with a lockfile. Replaces pip-sync. uv pip sync requirements.txt.`,
    },
    {
      title: 'Utility',
      route: '/guides/utility',
      content: `Utility Managing and inspecting uv's state such as the cache storage directories or performing a self-update. Clean cache Remove cache entries to free up disk space. uv cache clean. uv cache clean older 30d. Prune cache Remove outdated cache entries that are no longer needed. uv cache prune. uv cache prune dry-run. Cache directory Show the path to uv's cache directory. uv cache dir. Tool directory Show the path to uv's tool directory where installed tools are stored. uv tool dir. Python directory Show the path to uv's Python versions directory. uv python dir. Self-update Update uv to the latest version to get new features and bug fixes. uv self update.`,
    },
  ];

  search(query: string): SearchResult[] {
    if (!query || query.trim().length === 0) {
      return [];
    }

    const normalizedQuery = query.toLowerCase().trim();
    const results: SearchResult[] = [];

    for (const guide of this.guideIndex) {
      const normalizedContent = guide.content.toLowerCase();
      const normalizedTitle = guide.title.toLowerCase();

      // Check if query matches in title or content
      if (
        normalizedTitle.includes(normalizedQuery) ||
        normalizedContent.includes(normalizedQuery)
      ) {
        // Find the matched text snippet
        let matchedText = '';
        const queryIndex = normalizedContent.indexOf(normalizedQuery);

        if (queryIndex !== -1) {
          const start = Math.max(0, queryIndex - 30);
          const end = Math.min(guide.content.length, queryIndex + normalizedQuery.length + 50);
          matchedText = guide.content.substring(start, end).trim();
        } else if (normalizedTitle.includes(normalizedQuery)) {
          matchedText = guide.content.substring(0, 80).trim();
        }

        results.push({
          title: guide.title,
          route: guide.route,
          snippet: this.createSnippet(guide.content, normalizedQuery),
          matchedText,
        });
      }
    }

    return results;
  }

  private createSnippet(content: string, query: string): string {
    const index = content.toLowerCase().indexOf(query);
    if (index === -1) {
      return content.substring(0, 100) + '...';
    }

    const start = Math.max(0, index - 40);
    const end = Math.min(content.length, index + query.length + 60);
    let snippet = content.substring(start, end).trim();

    if (start > 0) snippet = '...' + snippet;
    if (end < content.length) snippet = snippet + '...';

    return snippet;
  }
}